- title: Mentor
  at: Purdue Mathematics Directed Reading Program
  location: West Lafayette, IN
  description: "Mentored [Dhruv Jain](https://www.linkedin.com/in/dhruvjain960/?originalSubdomain=in) in Elementary Algebraic Topology and Topological Data Analysis."
  years: Fall 2025
- title: Mentor
  at: Auburn Mathematics Directed Reading Program
  location: Auburn, AL
  description: "Guided student through advanced study in linear algebra."
  years: Fall 2024
- title: Judge
  at: Alabama Science and Engineering Fair
  location: Auburn, AL
  url: https://www.auburn.edu/cosam/outreach/stem_outreach/programs/asef/index.htm
  years: Spring 2024
- title: Co-organizer
  at: UAH Putnam Club
  location: Huntsville, AL
  years: 2022
- title: Math Tutor
  at: Danville Middle 
  location: Danville, AL
  years: 2018-2020

